#! /bin/sh

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         	2
bspc config window_gap          	12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle       	true
bspc config focus_follows_pointer 	true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a 'Tor Browser' state=floating
bspc rule -a Java state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### BSPWM coloring ####
bspc config normal_border_color	        "#1a1b26"
bspc config active_border_color		"#414868"
bspc config focused_border_color        "#565f89"
bspc config presel_feedback_color       "#5e81ac"
bspc config urgent_border_color         "#f7768e"


# Fix cursor.
xsetroot -cursor_name left_ptr

# Set Keyboard
setxkbmap us intl

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Start X wallpaper.
nitrogen --restore &

#Polybar refresh
$HOME/.config/polybar/launch.sh &
